"""
NetSentry Feature Engineering Module (`netsentry.features.engineer`)
-------------------------------------------------------------------
Generates deterministic, stateless domain features for network intrusion detection:
1. Packet & Byte Ratios (directional asymmetry, burst indicators).
2. Inter-Arrival Time (IAT) statistics & variance spreads.
3. TCP Flag interaction products (stealth scan and syn flood indicators).

Design Rule:
All transformations here are stateless (scale-invariant and parameter-free),
ensuring zero data leakage between Train, Validation, and Test sets.
"""

from typing import Union
import polars as pl


def compute_directional_ratios(df: pl.LazyFrame) -> pl.LazyFrame:
    """
    Computes asymmetric traffic ratios between forward and backward directions:
    - Packet ratio: Total_Fwd_Packets / (Total_Backward_Packets + 1)
    - Byte ratio: Total_Length_of_Fwd_Packets / (Total_Length_of_Bwd_Packets + 1)
    - Average packet payload sizes
    """
    schema = df.collect_schema().names()

    exprs = []
    if "Total_Fwd_Packets" in schema and "Total_Backward_Packets" in schema:
        exprs.append(
            (pl.col("Total_Fwd_Packets") / (pl.col("Total_Backward_Packets") + 1.0))
            .cast(pl.Float32)
            .alias("Fwd_to_Bwd_Packet_Ratio")
        )

    if "Total_Length_of_Fwd_Packets" in schema and "Total_Length_of_Bwd_Packets" in schema:
        exprs.append(
            (pl.col("Total_Length_of_Fwd_Packets") / (pl.col("Total_Length_of_Bwd_Packets") + 1.0))
            .cast(pl.Float32)
            .alias("Fwd_to_Bwd_Byte_Ratio")
        )

    if "Total_Length_of_Fwd_Packets" in schema and "Total_Fwd_Packets" in schema:
        exprs.append(
            (pl.col("Total_Length_of_Fwd_Packets") / (pl.col("Total_Fwd_Packets") + 1e-5))
            .cast(pl.Float32)
            .alias("Avg_Fwd_Packet_Payload")
        )

    return df.with_columns(exprs) if exprs else df


def compute_flag_interactions(df: pl.LazyFrame) -> pl.LazyFrame:
    """
    Computes interaction terms between TCP control flags (SYN, FIN, RST, ACK).
    Unusual combinations (e.g. SYN without ACK, or FIN+SYN) are high-confidence scan/DoS indicators.
    """
    schema = df.collect_schema().names()
    exprs = []

    if "SYN_Flag_Count" in schema and "ACK_Flag_Count" in schema:
        # SYN flood / stealth scan indicator: SYN high while ACK is 0
        exprs.append(
            (pl.col("SYN_Flag_Count") * (1.0 - pl.col("ACK_Flag_Count")))
            .cast(pl.Float32)
            .alias("SYN_no_ACK_Indicator")
        )

    if "RST_Flag_Count" in schema and "Total_Fwd_Packets" in schema:
        # Reset density indicator (port knocking / scanner resets)
        exprs.append(
            (pl.col("RST_Flag_Count") / (pl.col("Total_Fwd_Packets") + 1.0))
            .cast(pl.Float32)
            .alias("RST_Density")
        )

    return df.with_columns(exprs) if exprs else df


def compute_temporal_rate_features(df: pl.LazyFrame) -> pl.LazyFrame:
    """
    Computes flow throughput and packet density metrics per microsecond:
    - Log-transformed duration to compress massive multi-order-of-magnitude ranges
    - Packet density: (Total_Fwd_Packets + Total_Backward_Packets) / (Flow_Duration + 1)
    """
    schema = df.collect_schema().names()
    exprs = []

    if "Flow_Duration" in schema:
        # Stable log1p transform on non-negative duration
        exprs.append(
            (pl.col("Flow_Duration") + 1.0).log().cast(pl.Float32).alias("Log_Flow_Duration")
        )

    if "Total_Fwd_Packets" in schema and "Total_Backward_Packets" in schema and "Flow_Duration" in schema:
        exprs.append(
            ((pl.col("Total_Fwd_Packets") + pl.col("Total_Backward_Packets")) / (pl.col("Flow_Duration") + 1.0))
            .cast(pl.Float32)
            .alias("Flow_Packet_Density")
        )

    return df.with_columns(exprs) if exprs else df


def engineer_network_features(df: Union[pl.DataFrame, pl.LazyFrame]) -> pl.DataFrame:
    """
    Executes the stateless domain feature engineering pipeline:
    Directional Ratios -> Flag Interactions -> Temporal Rate Features.
    """
    lf = df.lazy() if isinstance(df, pl.DataFrame) else df

    lf = compute_directional_ratios(lf)
    lf = compute_flag_interactions(lf)
    lf = compute_temporal_rate_features(lf)

    # Collect and ensure no NaNs/Infs were generated by division
    res_df = lf.collect()
    return res_df.fill_nan(0.0).fill_null(0.0)